name: Testes Unitários

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs_on: ubuntu:latest
    steps:
      - name: Checkout branch.
        uses: actions/checkout@v3
      - name: Setup node.
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies.
        run: npm ci
      - name: Run tests.
        run: npm test
